---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins

helmCharts:
  - name: jenkins
    repo: https://charts.jenkins.io
    version: 5.8.14
    releaseName: jenkins
    namespace: jenkins
    includeCRDs: true
    # valuesMerge: merge
    valuesFile: values.yaml
    # additionalValuesFiles:
    # - casc-config-h.yaml

resources:
  - ingress.yaml # upstream helm ingress is stringent/finicky. kustomize is going to patch environments anyway
  - secrets.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: jenkins-scripts
    files:
    - pipeline1.groovy # refer to values.yaml `job-dsl:` for the auto-launch script
