apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: django # crucial for configMapGenerator
resources:
- deployment.yaml
- ingress.yaml
- pvc.yaml
- secrets.yaml
- service.yaml
- serviceaccount.yaml
- job.yaml # workaround for applicationset not supporting env substitution, using `preservedFields` in the appset
- rbac.yaml
configMapGenerator:
- name: nginx-config
  files:
  - ../../django-todo/nginx/default.conf # load the nginx default.conf from the django project directory
# the newTag: def below has a seemingly hardcoded string, but is updated by image updater dynamically, since it has access to both ECR and github repo
images:
- name: django-production-kustomize
  newName: 350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production2
  newTag: fcb99d51e736a478d779a2e0c16bd099f4123fbe
