---
# #argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-github-app-secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: argocd-secrets
    kind: SecretStore
  target:
    name: argocd-secrets
    creationPolicy: Owner
    immutable: true
  data:
    - secretKey: username
      remoteRef:
        key: "/argo/cd/image_updater/github/user"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: "/argo/cd/image_updater/github/token"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
#     - secretKey: CLUSTER_ECR_DOMAIN
#       remoteRef:
#         key: argo_cd_aws_ecr_repo
#         conversionStrategy: Default
#         decodingStrategy: None
#         metadataPolicy: None

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        jwt:  # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: argocd-image-updater # name of actual serviceAccount (not role) attached to IRSA
