# `secretEnvVars:` has to be updated in jenkins/values.yaml with each key (there's no envfrom in the chart)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-secrets
  namespace: prometheus
spec:
  refreshInterval: "0" # default 1h , should only be refreshed on deploy (?)
  secretStoreRef:
    name: prometheus-secrets # must match `SecretStore` name
    kind: SecretStore
  target:
    name: prometheus-secrets
    creationPolicy: Owner # Owner # Owner managed by ESO
    immutable: true # check

  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana_admin_user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: admin-password
      remoteRef:
        key: grafana_admin_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: prometheus-secrets
  namespace: prometheus
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1  # AWS region specific, pending dynamic value
      auth:
        jwt: # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: grafana # name of actual serviceAccount (not role)


