---
# `secretEnvVars:` has to be updated in jenkins/values.yaml with each key (there's no envfrom in the chart)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-secrets
  namespace: prometheus
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: prometheus-secrets
    kind: SecretStore
  target:
    name: prometheus-secrets
    creationPolicy: Owner
    immutable: true

  data:
    - secretKey: admin-user
      remoteRef:
        key: "/grafana/admin/username"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: admin-password
      remoteRef:
        key: "/grafana/admin/password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: prometheus-secrets
  namespace: prometheus
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        jwt: # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: kube-prometheus-stack-grafana # name of actual serviceAccount (not role)
