alertmanager:
  alertmanagerSpec:
    nodeSelector:
      role: ci-cd

kube-state-metrics:
  nodeSelector:
    role: ci-cd

prometheus-node-exporter:
  nodeSelector:
    role: ci-cd

grafana:
  admin:
    existingSecret: "prometheus-secrets"
    userKey: admin-user # key in secrets.yaml, not actual password
    passwordKey: admin-password # key in secrets.yaml, not actual password
  nodeSelector:
    role: ci-cd

prometheus:
  prometheusSpec:
    nodeSelector:
      role: ci-cd

prometheusOperator:
  admissionWebhooks:
    failurePolicy: Ignore # prometheus-kube-stack sync fix
    patch:
      ttlSecondsAfterFinished: 120 # prometheus-kube-stack sync fix
  nodeSelector:
      role: ci-cd

# Control plane is managed by EKS hence the following are disabled
defaultRules:
  rules:
    etcd: false
    kubeScheduler: false
    kubeControllerManager: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false

kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    interval: "30s"
    resource: false # disabled by default because container metrics are already exposed by cAdvisor
    resourcePath: "/metrics/resource"

