apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fluent

helmCharts:
  - name: fluent-operator # is able to install both fluentbit and fluentd
    repo: https://fluent.github.io/helm-charts
    version: 3.0.0 # (Chart 3.0.0, App 3.0.0)
    releaseName: fluent-operator
    namespace: fluent
    includeCRDs: true
    valuesFile: values.yaml

resources: # https://github.com/fluent/fluent-operator/tree/master/manifests/logging-stack
#  - output-elasticsearch.yaml
#  - serviceaccount.yaml # check name of created serviceAccount first
  - secrets.yaml
  - rbac.yaml

# adding patches to things that can't be disabled via the upstream chart
#patches:
#  - path: sa.yaml
#    target:
#      group: ""
#      version: v1
#      kind: ServiceAccount
#      name: fluent-operator
#      namespace: fluent
#
#patches:
#- patch: |-
#    - op: add
#      path: /metadata/annotations/eks.amazonaws.com~1role-arn
#      value: "arn:aws:iam::350206045032:role/FluentRole"
#  target:
#    group: v1
#    kind: ServiceAccount
#    name: fluent-operator
#    namespace: fluent
#
patches:
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: fluent-operator
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::350206045032:role/FluentRole2"
  target:
    kind: ServiceAccount
    name: fluent-operator
    namespace: fluent

#patches:
#  - target:
#      group: ""
#      version: v1
#      kind: ServiceAccount
#      name: fluent-operator
#      namespace: fluent
#    patch: |-
#      apiVersion: v1
#      kind: ServiceAccount
#      metadata:
#        annotations:
#          eks.amazonaws.com/role-arn: "arn:aws:iam::350206045032:role/FluentRole"
