apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: es
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  es:
    host: elasticsearch-es-http.eck-stack.svc
    port: 9200
    generateID: true
    bufferSize: 20MB
    traceError: true
    logstashPrefix: ks-logstash-log
    logstashFormat: true
    timeKey: "@timestamp"
    index: "fluent-bit"
    httpUser: "elastic"
    httpPassword: "y4Q4xwzD6IE5PS3iO3464lH6" # ${HTTP_PASSWORD} # testing hardcoded key before making it dynamic