apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: es
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  es:
    host: elasticsearch-es-http.eck-stack.svc
    port: 9200
    generateID: true
    bufferSize: 20MB
    traceError: true
    logstashPrefix: ks-logstash-log
    logstashFormat: true
    timeKey: "@timestamp"
    index: "fluent-bit"
    #httpUser: "elastic"
    httpUser:
      valueFrom:
        secretKeyRef:
          name: elasticsearch-es-elastic-user  # The secret name
          key: username  # The key within the secret holding the password
    httpPassword:
      valueFrom:
        secretKeyRef:
          name: elasticsearch-es-elastic-user  # The secret name
          key: password  # The key within the secret holding the password