containerRuntime: containerd
Kubernetes: true

operator:
  nodeSelector:
    role: "django" # this should go in its own nodegroup, but for the purpose of POC assigning group with enough memory
#  disableComponentControllers:
#    fluentd:
#      crdsEnable: false # ? "error": "incorrect value for `-disable-component-controllers` and it will not be proceeded (possible values are: fluent-bit, fluentd)"
#  annotations:
#    eks.amazonaws.com/role-arn: "arn:aws:iam::350206045032:role/FluentRole"

fluentbit:
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 25Mi
  logLevel: "error"
  nodeSelector:
    role: "django" # this should go in its own nodegroup, but for the purpose of POC assigning group with enough memory
  tolerations:
    - operator: Exists

  namespaceFluentBitCfgSelector: {}

  input:
    tail:
      enable: true
      # excludePath: /var/log/containers/utils_default_utils-*.log # # Exclude logs from util pod
      # parser: docker   #If it is a containerd environment, then this item should be set to cri
      multilineParser: "cri" # "docker, cri"
      refreshIntervalSeconds: 10
      memBufLimit: 15MB # limit of memory that Tail plugin can use when appending data to the Engine.
      bufferMaxSize: ""
      path: "/var/log/containers/*.log"
      skipLongLines: true
      readFromHead: false
      storageType: memory # # Use storageType as "filesystem" if you want to use filesystem as the buffering mechanism for tail input.
      pauseOnChunksOverlimit: "off" # default: "off"

    systemd:
      enable: true
      systemdFilter:
        enable: true
        filters:
          - _SYSTEMD_UNIT=kubelet.service
      path: "/var/log/journal"
      includeKubelet: true
      stripUnderscores: "off" # on?
      storageType: memory # Use storageType as "filesystem" if you want to use filesystem as the buffering mechanism for systemd input.
      pauseOnChunksOverlimit: "off"

  output:
    es:
      enable: true # true
      enableTLS: false
      tls:
        verify: Off
      host: elasticsearch-es-http.eck-stack.svc # http://elasticsearch-es-http.eck-stack.svc:9200/
      port: 9200
      bufferSize: "5MB" # 20MB # "4KB"
      logstashPrefix: logstash # # ks-logstash-log
      logstashPrefixKey: logstash # ks-logstash-log
      traceError: true # to debug fluentbit connection with es API (not about forwarding trace data in general)
      #traceOutput: true # to debug fluentbit connection with es API (not about forwarding trace data in general)
      logstashFormat: true # True/False, On,Off
      replaceDots: true
      writeOperation: create # upsert # Id_Key or Generate_ID needed for upsert. (default create)
      suppressTypeName: "On" # crucial for es 8.x and newer, _type not supported
      type: "doc" # crucial for es 8.x and newer, _type not supported
      #path: ""
      index: "fluent-bit"
      httpUser: #  elasticsearch API access creds ("x-pack")
        valueFrom:
          secretKeyRef:
            name: elastic-secrets # `elastic-secrets` is created twice for fluent and eck namespace, they refer to the same SSM parameters
            key: username # name of they key, not actual value
            optional: true
      httpPassword:
        valueFrom:
          secretKeyRef:
            name: elastic-secrets
            key: password # name of they key, not actual value
            optional: true

  # Configure the default filters in FluentBit.
  # The `filter` will filter and parse the collected log information and output the logs into a uniform format. You can choose whether to turn this on or not.
  filter:
    kubernetes:
      enable: true
      labels: false
      annotations: false
    containerd:
      # This is customized lua containerd log format converter, you can refer here:
      # https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/templates/fluentbit-clusterfilter-containerd.yaml
      # https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/templates/fluentbit-containerd-config.yaml
      enable: true
    systemd:
      enable: true

  # removes the hostPath mounts for varlibcontainers, varlogs and systemd.
  disableLogVolumes: false

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""