---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elastic-secrets
  namespace: eck-stack
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: elastic-secrets
    kind: SecretStore
  target:
    name: elastic-secrets
    creationPolicy: Owner
    immutable: true
  data:
    - secretKey: password
      remoteRef:
        key: "/elastic/api/password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: username
      remoteRef:
        key: "/elastic/api/username"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: roles
      remoteRef:
        key: "/elastic/api/roles"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: elastic-secrets
  namespace: elastic
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        jwt: # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: eck-pass # name of actual serviceAccount (not role)
