eck-elasticsearch:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  fullnameOverride: elasticsearch # must be reference in eck-kibana: elasticsearchRef:
  nodeSets:
  - name: default
    count: 1 # number of replicas
    config:
      node.store.allow_mmap: false # vm.max_map_count via initContainer # vm.max_map_count to 262144 # https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
      #telemetry.optIn: false
      xpack.security.authc: # Enable anonymous access to allow GCLB health probes to succeed # Ingress?
        anonymous:
          username: anon
          roles: monitoring_user
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 1Gi
                cpu: .5
              limits:
                memory: 2.5Gi
                cpu: 2
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: gp3

eck-kibana:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  fullnameOverride: kibana
  spec:
    config:
      telemetry.optIn: false
      telemetry.allowChangingOptInStatus: false
    http:
      tls:
        selfSignedCertificate:
          disabled: true # disable tls to account for ALB SSL termination
    count: 1 # number of replicas
    elasticsearchRef:
      name: elasticsearch # must match eck-elasticsearch: fullnameOverride:
    podTemplate:
      spec:
        containers:
          - name: kibana
            env:
              - name: NEWSFEED_ENABLED
                value: "false"
            resources:
              requests:
                memory: 1Gi
                cpu: .5
              limits:
                memory: 2.5Gi
                cpu: 2

eck-agent:
  enabled: false

eck-fleet-server:
  enabled: false

eck-beats:
  enabled: false

eck-logstash:
  enabled: false

eck-apm-server:
  enabled: false

eck-enterprise-search:
  enabled: false