eck-elasticsearch:
  telemetry:
    disabled: true
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  fullnameOverride: elasticsearch # must be reference in eck-kibana: elasticsearchRef:
  nodeSets: # check indentations for nodeSets, they are different in the documentation examples
  - name: default
    count: 1 # 3 min ?
    config:
      node.store.allow_mmap: false # vm.max_map_count via initContainer # vm.max_map_count to 262144 # https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
      xpack.security.authc: # Enable anonymous access to allow GCLB health probes to succeed # Ingress?
        anonymous:
          username: anon
          roles: monitoring_user
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 1Gi # Default 1Gi # check
                cpu: 1
              limits:
                memory: 1Gi # check
                cpu: 1
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: gp3

eck-kibana:
  telemetry:
    disabled: true
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  #fullnameOverride: kibana
  spec:
    count: 1 # number of replicas
    elasticsearchRef:
      name: elasticsearch # must match eck-elasticsearch: fullnameOverride:
    podTemplate:
      spec:
        containers:
          - name: kibana
            env:
              - name: NODE_OPTIONS
                value: "--max-old-space-size=2048"
            resources:
              requests:
                memory: 1Gi # Default 1Gi # check
                cpu: 1
              limits:
                memory: 2.5Gi
                cpu: 2

eck-agent:
  enabled: false

eck-fleet-server:
  enabled: false

eck-beats:
  enabled: false

eck-logstash:
  enabled: false

eck-apm-server:
  enabled: false

eck-enterprise-search:
  enabled: false