---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-secrets
  namespace: sonarqube
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: sonarqube-secrets
    kind: SecretStore
  target:
    name: sonarqube-secrets
    creationPolicy: Owner
    immutable: true

  data:
    - secretKey: SONAR_JDBC_USERNAME
      remoteRef:
        key: "/sonar/db/username"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: SONAR_JDBC_PASSWORD
      remoteRef:
        key: "/sonar/db/password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: SONAR_JDBC_URL # it's `SONAR_JDBC_URL` not `SONARQUBE_JDBC_URL` # chart error
      remoteRef:
        key: "/sonar/db/endpoint"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: sonar_rds_dbname
      remoteRef:
        key: "/sonar/db/name"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: sonar_rds_port
      remoteRef:
        key: "/sonar/db/port"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: sonar_token
      remoteRef:
        key: "/sonar/db/token"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: password
      remoteRef:
        key: "/sonar/admin/password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: currentPassword
      remoteRef:
        key: "/sonar/admin/password_current"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sonarqube-secrets
  namespace: sonarqube
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        jwt: # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: sonarqube # name of actual serviceAccount (not role)
