apiVersion: batch/v1
kind: Job
metadata:
  name: make-fluentoperator-load-externalsecrets
  namespace: fluent
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    #argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      serviceAccountName: fluent-operator
      containers:
      - name: kubectl-fluent-pass
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: # add fluent operator serviceAccount annotation
        - /bin/sh
        - -c
        - |
          kubectl patch sa fluent-operator -n fluent --type='merge' -p='{"metadata": {"annotations": {"eks.amazonaws.com/role-arn": "arn:aws:iam::${ARGOCD_AWS_ACCOUNT}:role/FluentRole"}}}'
      restartPolicy: Never