apiVersion: v1
kind: ServiceAccount
metadata:
#  labels:
#    app.kubernetes.io/component: operator
#    app.kubernetes.io/name: fluent-operator
  name: fluent-operator
  namespace: fluent
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${ARGOCD_AWS_ACCOUNT}:role/FluentRole"