---
# placeholder for changing argocd admin password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: argocd-secrets
    kind: SecretStore
  target:
    name: argocd-secrets
    creationPolicy: Owner
    immutable: true
  data:
    - secretKey: ARGOCD_ADMIN_PASSWORD
      remoteRef:
        key: "/argo/cd/admin/password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        jwt:  # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: argo-cd-argocd-server # argo-cd-argocd-repo-server # name of actual serviceAccount (not role) attached to IRSA
