---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - secrets.yaml
  - argocd-helm.yaml
  - ingress.yaml
  - rbac.yaml

patches:
  - path: init-container.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
      namespace: argocd
