---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secrets-global
  namespace: argocd
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: argocd-secrets-global
    kind: SecretStore
  target:
    name: argocd-secrets-global
    creationPolicy: Owner
    immutable: true
  data:
    - secretKey: AWS_ACCOUNT_ID
      remoteRef:
        key: "aws/account_id"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: AWS_REGION
      remoteRef:
        key: "aws/region"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: ARGOCD_AWS_CLUSTER_NAME
      remoteRef:
        key: "cluster/name"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: ARGOCD_AWS_ECR_REPO
      remoteRef:
        key: "ecr/repo_domain"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: ARGOCD_APP_DOMAIN
      remoteRef:
        key: "cluster/domain"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: argocd-secrets-global
  namespace: argocd
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        jwt: # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: argo-cd-argocd-repo-server # name of actual serviceAccount (not role) attached to IRSA
