---
crds:
  keep: false

global:
  domain: argocd.hansohn.io
  nodeSelector:
    role: core

configs:
  params:
    server.insecure: true
    applicationsetcontroller.enable.progressive.syncs: true # ApplicationSet compatible with Progressive Syncs. (SyncWave must use app of apps)
    applicationsetcontroller.default.application.progressing.timeout: 1200 # When using rollingSync, prevent sync timeout error with kube prometheus stack (default 300 seconds)
  cmp:
    create: true
    plugins:
      envsubst:
        init:
          command: ["sh", "-c"]
          args: ["kustomize build . --load-restrictor LoadRestrictionsNone -o raw-kustomization.yaml"]
        generate:
          command: ["sh", "-c"]
          args: ["envsubst < raw-kustomization.yaml > processed-kustomization.yaml && cp processed-kustomization.yaml /dev/stdout"]
      substitution:
        init:
          command: ["/bin/sh", "-c"]
          args: ["echo initializing..."]
        generate:
          command: ["/bin/sh", "-c"]
          args:
            - |
              AVAILABLE_VARS=$(env | cut -d "=" -f 1 | awk '{print "$"$1}' | tr "\n" " ")
              kustomize build . --load-restrictor LoadRestrictionsNone --enable-helm | envsubst "$AVAILABLE_VARS"
        preserveFileMode: true
        allowConcurrency: true  # alt approach for cmp https://medium.com/@jojoooo/deploy-infra-stack-using-self-managed-argocd-with-cert-manager-externaldns-external-secrets-op-640fe8c1587b
  secret:
    createSecret: true

dex:
  enabled: false

server:
  ingress:
    enabled: false

repoServer:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  extraContainers:
    - name: substitution
      command: ["/bin/sh", "-c"]
      args: # restart argocd-cmp-server (via kill -9) for envFrom to become effective
        - |
          /var/run/argocd/argocd-cmp-server
          sleep 5
          SERVER_PID=$(ps aux | grep '[a]rgocd-cmp-server' | awk '{print $2}')
          kill -9 $SERVER_PID
      envFrom:
        - secretRef:
            name: argocd-secrets-global
            optional: true
      image: tbalza/envsubst:latest
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: var-files
          mountPath: /var/run/argocd
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
        - name: argocd-cmp-cm
          mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: substitution.yaml
        - name: cmp-tmp
          mountPath: /tmp
  volumes:
    - name: argocd-cmp-cm
      configMap:
        name: argocd-cmp-cm
    - name: cmp-tmp
      emptyDir: {}
  rbac:
    - apiGroups:
        - "*"
      resources:
        - "*"
      verbs:
        - "*"
